server:
  port: 8080

security:
  jwt:
    expiration-time-minutes: 300
    signing-key: 5X4DZyu9TM2O3NdJcSr

spring:
  datasource:
    url: jdbc:postgresql://ec2-52-204-20-42.compute-1.amazonaws.com:5432/d3jcklh61ebtk2
    username: kbrbigxmthwapa
    password: 2b5c7d00e4d7ca60538023b19954967640e362deb983bdae669504a80f69c657

  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  thymeleaf:
    cache: false