server:
  port: 8080

security:
  jwt:
    expiration-time-minutes: 9000000
    signing-key: 5X4DZyu9TM2O3NdJcSr

spring:
  profiles:
    active: test

  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  thymeleaf:
    cache: false
